name: WebRTC iOS Static Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'WebRTC branch (e.g., master or branch-heads/6167)'
        required: true
        default: "branch-heads/0000"
        type: string

jobs:
  Build-Script:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Building WebRTC framework
        run: |
          sh clean.sh
          sh scripts/build_ios_static.sh
        env:
          BRANCH: ${{ inputs.branch }}
          IOS: true
          MACOS: false
          MAC_CATALYST: false
          BUILD_VP9: true
      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: libwebrtc.a
          path: src/out/libwebrtc.a
